#pragma config(StandardModel, "SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
motor[rightMotor]=50;
motor[leftMotor]=-50;
wait1Msec(13000);
}
