#pragma config(Sensor, in3,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in4,    light,          sensorReflection)
#pragma config(Sensor, in6,    accelZ,         sensorAccelerometer)
#pragma config(Sensor, in7,    accelY,         sensorAccelerometer)
#pragma config(Sensor, in8,    accelX,         sensorAccelerometer)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  frontTouch,     sensorTouch)
#pragma config(Sensor, dgtl8,  sonarCM,        sensorSONAR_cm)
#pragma config(Sensor, dgtl11, backTouch,      sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, driveRight, encoderPort, dgtl1)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop, driveLeft, encoderPort, dgtl3)
#pragma config(Motor,  port6,           armMotor,      tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	wait1Msec(2000);

	//*!! Leg 1 !!*//
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while(SensorValue[leftEncoder] < 4900)
	{
		motor[rightMotor] = 63;
		motor[leftMotor] = 52;
	}

	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
	wait1Msec(1000);

	//*!! Turn 1 !!*//
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while(SensorValue[leftEncoder] > -285)
	{
		motor[rightMotor] = 63;
		motor[leftMotor] = -63;
	}

	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
	wait1Msec(1000);

	//*!! Leg 2 !!*//
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while((SensorValue[leftEncoder] < 1900))
	{
		motor[rightMotor] = 63;
		motor[leftMotor] = 55;
	}

	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
	wait1Msec(1000);

	//*!! Turn 2 !!*//
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while(SensorValue[leftEncoder] > -140)
	{
		motor[rightMotor] = 63;
		motor[leftMotor] = -63;
	}

	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
	wait1Msec(1000);

	//*!! Leg 3 !!*//
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while((SensorValue[leftEncoder] < 5000))
	{
		motor[rightMotor] = 63;
		motor[leftMotor] = 52;
	}

	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
	wait1Msec(1000);

}
