#pragma config(StandardModel, "SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int x = 1;
	if(SensorValue[dgtl12]==true)
	{
		x+1;
	}

	if(x>1)
	{
		motor[port2] = 50;
		motor[port3] = 50;
		wait1Msec(13000);
	}
}
