#pragma config(StandardModel, "SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Wave arm function//
void wave(int time)
{
 motor[armMotor] = 60;
 wait1Msec(time/6);
 motor[armMotor] = -60;
 wait1Msec(time/6);

 motor[armMotor] = 60;
 wait1Msec(time/6);
 motor[armMotor] = -60;
 wait1Msec(time/6);

 motor[armMotor] = 60;
 wait1Msec(time/6);
 motor[armMotor] = -60;
 wait1Msec(time/6);
}

task main()
{

while (1 == 1)
{
	//Single Joystick Control//
	motor[leftMotor] = (vexRT[ch2] + vexRT[ch1])/2;
	motor[rightMotor] = (vexRT[ch2] - vexRT[ch1])/2;

	//Arm Control//
	if(vexRT[Btn6U] == 1)
	{
		motor[armMotor] = 60;
	}
	else if(vexRT[Btn6D] == 1)
	{
		motor[armMotor] = -60;
	}
	else
	{
		motor[armMotor] = 0;
	}

	//Trigger Wave Arm Function
	if(vexRT[Btn8U] == 1)
	{
		wave(3000)
	}
	else
	{
		motor[armMotor] = 0;
	}
}

}
