#pragma config(StandardModel, "SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
//*Forward*//
motor[leftMotor] = 127;
motor[rightMotor] = 127;
wait1Msec(1139);
motor[leftMotor] = 0;
motor[rightMotor] = 0;

//*Headbang*//
motor[armMotor] = 127;
wait1Msec(90.6);
motor[armMotor] = -127;
wait1Msec(90.6);
motor[armMotor] = 127;
wait1Msec(90.6);
motor[armMotor] = -127;
wait1Msec(90.6);
motor[armMotor] = 127;
wait1Msec(90.6);
motor[armMotor] = -127;
wait1Msec(90.6);

//*Pause*//
motor[armMotor] = 0;
wait1Msec(400);

//*Headbang*//
motor[armMotor] = 127;
wait1Msec(100);
motor[armMotor] = -127;
wait1Msec(100);
motor[armMotor] = 127;
wait1Msec(100);
motor[armMotor] = -127;
wait1Msec(100);
motor[armMotor] = 127;
wait1Msec(100);

//*Pause*//
motor[armMotor] = 0;
wait1Msec(300);

}
