#pragma config(StandardModel, "SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//*Declaring prototype of function*//
void sausageright(int timeVal);
void sausageleft(int timeVal);

//*Headbang Function*//
void headbang(int headbang)
{
	while (headbang > 0)
	{
		motor[armMotor] = 60;
		wait1Msec(90.6);
		motor[armMotor] = -60;
		wait1Msec(90.6);
		headbang = headbang - 1;
	}
	motor[armMotor] = 0;
}

//*Suspension function*//
void suspense(int counts)
{
	while(counts > 0)
	{
		wait1Msec(748.8);
		headbang(1);
		counts = counts - 1;
	}

}

//*Swing Right Function*//
void swingright(int time)
{
	motor[leftMotor] = -60;
	wait1Msec(time);
	motor[leftMotor] = 0;
}

//*Swing Left Function*//
void swingleft(int time)
{
	motor[rightMotor] = -60;
	wait1Msec(time);
	motor[rightMotor] = 0;
}

//*Big Circle Right Function*//
//int timeVal1 = 2790;
int timeVal1 = 2750;
int timeVal2 = 3650;

task bigright()
{
	sausageright(timeVal1);
}

task bigright2()
{
	sausageright(timeVal2);
}

void sausageright(int timeVal)
{
	motor[leftMotor] = 40;
	motor[rightMotor] = 10;
	wait1Msec(timeVal);
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
}

//*Big Circle Left Function*//
int timeVal3 = 3640;

task bigleft()
{
	sausageleft(timeVal3);
}

void sausageleft(int timeVal)
{
	motor[leftMotor] = 10;
	motor[rightMotor] = 40;
	wait1Msec(timeVal);
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
}

task main()
{

while (SensorValue[backTouch] == 0)
{

}

//*Forward*//
motor[leftMotor] = 60;
motor[rightMotor] = 60;
wait1Msec(1139);
motor[leftMotor] = 0;
motor[rightMotor] = 0;

//*Headbang*//
headbang(3);

//*Pause*//
motor[armMotor] = 0;
wait1Msec(400);

//*Headbang*//
headbang(3);

//*Pause*//
motor[armMotor] = 0;
wait1Msec(300);

//*Headbang*//
headbang(6);
//Time is 4013.4//

//*Backward*//
motor[leftMotor] = -60;
motor[rightMotor] = -60;
wait1Msec(686.6);
motor[leftMotor] = 0;
motor[rightMotor] = 0;
//Time is 4700//

//*Backward swing right*//
swingright(910);
//*Time is 5610*//

//*Backward swing left *//
swingleft(1020);
//*Time is 6630*//

//*Headbang*//
headbang(6);
//*Time is 7717.2*//

//*Pause*//
wait1Msec(562.8);
//*Time is 8280*//

//*Backward swing left*//
swingleft(930);
//*Time is 9210*//

//*Backward swing right*//
swingright(1120);
//*Time is 10330*//

//*Headbang*//
headbang(6);
//*Time is 11417.2*//

//*Pause*//
wait1Msec(682.8);
//*Time is 12100*//

//*Headbang*//
headbang(2);
//*Time is 12462.4*//

//*Pause*//
wait1Msec(407.6);
//*Time is 12870*//

//*Headbang*//
headbang(2);
//*Time is 13232.4*//

//*Pause*//
wait1Msec(757.6);
//*Time is 13990*//

//*Headbang*//
headbang(6);
//*Time is 15077.2*//

//*Forward*//
motor[leftMotor] = 60;
motor[rightMotor] = 60;
wait1Msec(832.8);
motor[leftMotor] = 0;
motor[rightMotor] = 0;
//*Time is 15910*//

//*Turn right in big circle*//
startTask(bigright);
headbang(4);
	//*Time is 16634.8*//
wait1Msec(195.2);
	//*Time is 16830*//
headbang(4);
	//*Time is 17554.8*//
wait1Msec(215.2);
	//*Time is 17770*//
headbang(5);
wait1Msec(24);
//*Time is 18700*//

//*Turn left in big circle*//
startTask(bigleft);
wait1Msec(880);
	//*Time is 19580*//
headbang(3);
	//*Time is 20123.6*//
wait1Msec(396.4);
	//*Time is 20520*//
headbang(4);
	//*Time is 21244.8*//
wait1Msec(205.2);
	//*Time is 21450*//
headbang(5);
wait1Msec(44);
//*Time is 22400*//

//*Turn right in big circle*//
startTask(bigright2);
wait1Msec(870);
	//*Time is 23270*//
headbang(3);
	//*Time is 23813.6*//
wait1Msec(396.4);
	//*Time is 24210*//
headbang(4);
	//*Time is 24934.8*//
wait1Msec(205.2);
	//*Time is 25140*//
headbang(5);
wait1Msec(34);
//*Time is 26080*//

//*Turn left in big circle*//
startTask(bigleft);
wait1Msec(870);
	//*Time is 26950*//
headbang(3);
	//*Time is 27493.6*//
wait1Msec(396.4);
	//*Time is 27890*//
headbang(4);
	//*Time is 28614.8*//
wait1Msec(205.2);
	//*Time is 28820*//
headbang(5);
wait1Msec(54);
//*Time is 29780*//

wait1Msec(920);
//*Time is 30700*//
headbang(1);
//*Time is 30881.2*//

wait1Msec(718.8);
headbang(1);
//*Time is 31781.2*//

suspense(13);
//*Time is 43871.2*//

wait1Msec(628.8);
//*Time is 44300*//
//SWITCH SONGS//

swingleft(2500);
//Time is 46800//

motor[leftMotor] = 60;
motor[rightMotor] = 60;
wait1Msec(1380);
motor[leftMotor] = 0;
motor[rightMotor] = 0;
//Time is 48180//

swingright(2310);
//Time is 50490//

motor[leftMotor] = -60;
motor[rightMotor] = -60;
wait1Msec(1390);
motor[leftMotor] = 0;
motor[rightMotor] = 0;
//Time is 51880//

swingleft(2290);
//Time is 54170//

headbang(7);
//Time is 55478.4//

}
