#pragma config(StandardModel, "SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

wait1Msec(2000);

while(SensorValue(sonarCM) > 20 || SensorValue(sonarCM) == -1)
{
	motor[leftMotor] = 32;
	motor[rightMotor] = 32;
}


}
