#pragma config(StandardModel, "SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
motor[rightMotor] = 50;
motor[leftMotor] = 50;
wait1Msec(3000);

motor[leftMotor] = 127;
motor[rightMotor] = -127;
wait1Msec(375);

motor[rightMotor] = 50;
motor[leftMotor] = 50;
wait1Msec(3000);
}
